stages:
- name: Publish image
  steps:
  - publishImageConfig:
      dockerfilePath: ./nginx/Dockerfile
      buildContext: ./nginx
      tag: nginx:${CICD_EXECUTION_SEQUENCE}
- name: Deploy
  steps:
  - applyYamlConfig:
      path: ./deploy/deployment.yaml
