kind: Service
apiVersion: v1
metadata:
  name: web-service
spec:
  selector:
    app: web
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  labels:
    app: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      volumes:
      - name: magento2-data
        persistentVolumeClaim:
                claimName: appdata
      imagePullSecrets:
      - name: pipeline-docker-registry
      containers:
      - name: nginx
        image: ${CICD_IMAGE}:${CICD_EXECUTION_SEQUENCE}
        volumeMounts:
           - name: magento2-data
             mountPath: "/var/www/magento"
        ports:
        - containerPort: 80

